volumes:
  file-volumes:

services:
  web:
    build: .
    restart: always
    ports:
      - 8080:8080
    volumes:
      - "~/ilovehk/assets:/app/public/assets"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ilovehk
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - "~/ilovehk/assets-data:/data/db"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://ilovehk:password@mongo:27017/
