volumes:
  file-volumes:

services:
  file-server:
    build: .
    image: ben39053372/file-server
    restart: always
    ports:
      - 8080:8080
    volumes:
      - "~/ilovehk/assets:/app/public/assets"
    depends_on:
      - mongo
    environment:
      DB_URI: mongodb://ilovehk:password@mongo:27017/
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ilovehk
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - "~/ilovehk/assets-data:/data/db"
